### ISSUE TITLE
ImportError occurs.

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [oHjm/face_and_gender#1]
I tried to use your program.
But the following error occured.

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "face_age_gender.py", line 28, in <module>
    from wide_resnet import WideResNet
  File "/content/face_and_gender/wide_resnet.py", line 6, in <module>
    from keras.models import Model
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/multi_gpu_utils.py", line 11, in <module>
    from ..models import clone_model
  File "/usr/local/lib/python3.7/dist-packages/keras/models.py", line 14, in <module>
    from .engine.saving import save_model
ImportError: cannot import name 'save_model' from 'keras.engine.saving' (/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py)
```

I think this cause is about version of libraries.
So, please let me know the versions you used.

**Comment by oHjm** [comment]
Duplicate of #1
@Ishihara-Masabumi 

Thank you for using my program.
Also, I'm sorry for not writing the versions.

The following versions is needed to run this program.
 Environment
-Python: 3.6.6
-OpenCV: 4.2.0.32
-numpy:1.16.1
-tensorflow:1.6.0
-keras:2.2.0
-scipy:1.2.0

Please contact me if you have any further questions.

**Comment by Ishihara-Masabumi** [comment]
Thank you!
